/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssistantFile model module.
 * @module model/AssistantFile
 * @version 0.1.0
 */
class AssistantFile {
    /**
     * Constructs a new <code>AssistantFile</code>.
     * @alias module:model/AssistantFile
     * @param id {String} The unique identifier of the file.
     * @param createdAt {Number} The unix timestamp of when the file was created.
     * @param assistantId {String} The unique identifier of the assistant.
     */
    constructor(id, createdAt, assistantId) { 
        
        AssistantFile.initialize(this, id, createdAt, assistantId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, assistantId) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['assistant_id'] = assistantId;
    }

    /**
     * Constructs a <code>AssistantFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssistantFile} obj Optional instance to populate.
     * @return {module:model/AssistantFile} The populated <code>AssistantFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssistantFile();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('assistant_id')) {
                obj['assistant_id'] = ApiClient.convertToType(data['assistant_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssistantFile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssistantFile</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssistantFile.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['assistant_id'] && !(typeof data['assistant_id'] === 'string' || data['assistant_id'] instanceof String)) {
            throw new Error("Expected the field `assistant_id` to be a primitive type in the JSON string but got " + data['assistant_id']);
        }

        return true;
    }


}

AssistantFile.RequiredProperties = ["id", "created_at", "assistant_id"];

/**
 * The unique identifier of the file.
 * @member {String} id
 */
AssistantFile.prototype['id'] = undefined;

/**
 * @member {String} object
 * @default 'assistant.file'
 */
AssistantFile.prototype['object'] = 'assistant.file';

/**
 * The unix timestamp of when the file was created.
 * @member {Number} created_at
 */
AssistantFile.prototype['created_at'] = undefined;

/**
 * The unique identifier of the assistant.
 * @member {String} assistant_id
 */
AssistantFile.prototype['assistant_id'] = undefined;






export default AssistantFile;

