/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Choice from './Choice';
import UsageStatistics from './UsageStatistics';

/**
 * The ChatCompletionResponse model module.
 * @module model/ChatCompletionResponse
 * @version 0.1.0
 */
class ChatCompletionResponse {
    /**
     * Constructs a new <code>ChatCompletionResponse</code>.
     * https://platform.openai.com/docs/api-reference/chat/object
     * @alias module:model/ChatCompletionResponse
     * @param id {String} 
     * @param choices {Array.<module:model/Choice>} 
     * @param created {Date} 
     * @param usage {module:model/UsageStatistics} 
     */
    constructor(id, choices, created, usage) { 
        
        ChatCompletionResponse.initialize(this, id, choices, created, usage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, choices, created, usage) { 
        obj['id'] = id;
        obj['choices'] = choices;
        obj['created'] = created;
        obj['usage'] = usage;
    }

    /**
     * Constructs a <code>ChatCompletionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChatCompletionResponse} obj Optional instance to populate.
     * @return {module:model/ChatCompletionResponse} The populated <code>ChatCompletionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChatCompletionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], [Choice]);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('system_fingerprint')) {
                obj['system_fingerprint'] = ApiClient.convertToType(data['system_fingerprint'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = UsageStatistics.constructFromObject(data['usage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChatCompletionResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChatCompletionResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChatCompletionResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['choices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['choices'])) {
                throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
            }
            // validate the optional field `choices` (array)
            for (const item of data['choices']) {
                Choice.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['system_fingerprint'] && !(typeof data['system_fingerprint'] === 'string' || data['system_fingerprint'] instanceof String)) {
            throw new Error("Expected the field `system_fingerprint` to be a primitive type in the JSON string but got " + data['system_fingerprint']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // validate the optional field `usage`
        if (data['usage']) { // data not null
          UsageStatistics.validateJSON(data['usage']);
        }

        return true;
    }


}

ChatCompletionResponse.RequiredProperties = ["id", "choices", "created", "usage"];

/**
 * @member {String} id
 */
ChatCompletionResponse.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/Choice>} choices
 */
ChatCompletionResponse.prototype['choices'] = undefined;

/**
 * @member {Date} created
 */
ChatCompletionResponse.prototype['created'] = undefined;

/**
 * @member {String} model
 */
ChatCompletionResponse.prototype['model'] = undefined;

/**
 * @member {String} system_fingerprint
 */
ChatCompletionResponse.prototype['system_fingerprint'] = undefined;

/**
 * @member {module:model/ChatCompletionResponse.ObjectEnum} object
 * @default 'chat.completion'
 */
ChatCompletionResponse.prototype['object'] = 'chat.completion';

/**
 * @member {module:model/UsageStatistics} usage
 */
ChatCompletionResponse.prototype['usage'] = undefined;





/**
 * Allowed values for the <code>object</code> property.
 * @enum {String}
 * @readonly
 */
ChatCompletionResponse['ObjectEnum'] = {

    /**
     * value: "chat.completion"
     * @const
     */
    "chat.completion": "chat.completion"
};



export default ChatCompletionResponse;

