/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteThreadResponse model module.
 * @module model/DeleteThreadResponse
 * @version 0.1.0
 */
class DeleteThreadResponse {
    /**
     * Constructs a new <code>DeleteThreadResponse</code>.
     * @alias module:model/DeleteThreadResponse
     * @param id {String} The unique identifier of the agent.
     * @param deleted {Boolean} Whether the agent was deleted.
     */
    constructor(id, deleted) { 
        
        DeleteThreadResponse.initialize(this, id, deleted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, deleted) { 
        obj['id'] = id;
        obj['deleted'] = deleted;
    }

    /**
     * Constructs a <code>DeleteThreadResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteThreadResponse} obj Optional instance to populate.
     * @return {module:model/DeleteThreadResponse} The populated <code>DeleteThreadResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteThreadResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteThreadResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteThreadResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteThreadResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }

        return true;
    }


}

DeleteThreadResponse.RequiredProperties = ["id", "deleted"];

/**
 * The unique identifier of the agent.
 * @member {String} id
 */
DeleteThreadResponse.prototype['id'] = undefined;

/**
 * @member {String} object
 * @default 'thread.deleted'
 */
DeleteThreadResponse.prototype['object'] = 'thread.deleted';

/**
 * Whether the agent was deleted.
 * @member {Boolean} deleted
 */
DeleteThreadResponse.prototype['deleted'] = undefined;






export default DeleteThreadResponse;

