/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FunctionCall1 from './FunctionCall1';

/**
 * The FunctionCallMessage model module.
 * @module model/FunctionCallMessage
 * @version 0.1.0
 */
class FunctionCallMessage {
    /**
     * Constructs a new <code>FunctionCallMessage</code>.
     * {     \&quot;function_call\&quot;: {         \&quot;name\&quot;: function_call.function.name,         \&quot;arguments\&quot;: function_call.function.arguments,     },     \&quot;id\&quot;: str(msg_obj.id),     \&quot;date\&quot;: msg_obj.created_at.isoformat(), }
     * @alias module:model/FunctionCallMessage
     * @param id {String} 
     * @param date {Date} 
     * @param functionCall {module:model/FunctionCall1} 
     */
    constructor(id, date, functionCall) { 
        
        FunctionCallMessage.initialize(this, id, date, functionCall);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, date, functionCall) { 
        obj['id'] = id;
        obj['date'] = date;
        obj['function_call'] = functionCall;
    }

    /**
     * Constructs a <code>FunctionCallMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FunctionCallMessage} obj Optional instance to populate.
     * @return {module:model/FunctionCallMessage} The populated <code>FunctionCallMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FunctionCallMessage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('function_call')) {
                obj['function_call'] = FunctionCall1.constructFromObject(data['function_call']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FunctionCallMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FunctionCallMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FunctionCallMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `function_call`
        if (data['function_call']) { // data not null
          FunctionCall1.validateJSON(data['function_call']);
        }

        return true;
    }


}

FunctionCallMessage.RequiredProperties = ["id", "date", "function_call"];

/**
 * @member {String} id
 */
FunctionCallMessage.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
FunctionCallMessage.prototype['date'] = undefined;

/**
 * @member {module:model/FunctionCall1} function_call
 */
FunctionCallMessage.prototype['function_call'] = undefined;






export default FunctionCallMessage;

