/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LegacyFunctionCallMessage model module.
 * @module model/LegacyFunctionCallMessage
 * @version 0.1.0
 */
class LegacyFunctionCallMessage {
    /**
     * Constructs a new <code>LegacyFunctionCallMessage</code>.
     * @alias module:model/LegacyFunctionCallMessage
     * @param id {String} 
     * @param date {Date} 
     * @param functionCall {String} 
     */
    constructor(id, date, functionCall) { 
        
        LegacyFunctionCallMessage.initialize(this, id, date, functionCall);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, date, functionCall) { 
        obj['id'] = id;
        obj['date'] = date;
        obj['function_call'] = functionCall;
    }

    /**
     * Constructs a <code>LegacyFunctionCallMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LegacyFunctionCallMessage} obj Optional instance to populate.
     * @return {module:model/LegacyFunctionCallMessage} The populated <code>LegacyFunctionCallMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LegacyFunctionCallMessage();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('function_call')) {
                obj['function_call'] = ApiClient.convertToType(data['function_call'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LegacyFunctionCallMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LegacyFunctionCallMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LegacyFunctionCallMessage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['function_call'] && !(typeof data['function_call'] === 'string' || data['function_call'] instanceof String)) {
            throw new Error("Expected the field `function_call` to be a primitive type in the JSON string but got " + data['function_call']);
        }

        return true;
    }


}

LegacyFunctionCallMessage.RequiredProperties = ["id", "date", "function_call"];

/**
 * @member {String} id
 */
LegacyFunctionCallMessage.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
LegacyFunctionCallMessage.prototype['date'] = undefined;

/**
 * @member {String} function_call
 */
LegacyFunctionCallMessage.prototype['function_call'] = undefined;






export default LegacyFunctionCallMessage;

