/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LLMConfig from './LLMConfig';

/**
 * The ListModelsResponse model module.
 * @module model/ListModelsResponse
 * @version 0.1.0
 */
class ListModelsResponse {
    /**
     * Constructs a new <code>ListModelsResponse</code>.
     * @alias module:model/ListModelsResponse
     * @param models {Array.<module:model/LLMConfig>} List of model configurations.
     */
    constructor(models) { 
        
        ListModelsResponse.initialize(this, models);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, models) { 
        obj['models'] = models;
    }

    /**
     * Constructs a <code>ListModelsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListModelsResponse} obj Optional instance to populate.
     * @return {module:model/ListModelsResponse} The populated <code>ListModelsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListModelsResponse();

            if (data.hasOwnProperty('models')) {
                obj['models'] = ApiClient.convertToType(data['models'], [LLMConfig]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListModelsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListModelsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListModelsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['models']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['models'])) {
                throw new Error("Expected the field `models` to be an array in the JSON data but got " + data['models']);
            }
            // validate the optional field `models` (array)
            for (const item of data['models']) {
                LLMConfig.validateJSON(item);
            };
        }

        return true;
    }


}

ListModelsResponse.RequiredProperties = ["models"];

/**
 * List of model configurations.
 * @member {Array.<module:model/LLMConfig>} models
 */
ListModelsResponse.prototype['models'] = undefined;






export default ListModelsResponse;

