/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LogProbToken model module.
 * @module model/LogProbToken
 * @version 0.1.0
 */
class LogProbToken {
    /**
     * Constructs a new <code>LogProbToken</code>.
     * @alias module:model/LogProbToken
     * @param token {String} 
     * @param logprob {Number} 
     * @param bytes {Array.<Number>} 
     */
    constructor(token, logprob, bytes) { 
        
        LogProbToken.initialize(this, token, logprob, bytes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, logprob, bytes) { 
        obj['token'] = token;
        obj['logprob'] = logprob;
        obj['bytes'] = bytes;
    }

    /**
     * Constructs a <code>LogProbToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LogProbToken} obj Optional instance to populate.
     * @return {module:model/LogProbToken} The populated <code>LogProbToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LogProbToken();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('logprob')) {
                obj['logprob'] = ApiClient.convertToType(data['logprob'], 'Number');
            }
            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LogProbToken</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LogProbToken</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LogProbToken.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['bytes'])) {
            throw new Error("Expected the field `bytes` to be an array in the JSON data but got " + data['bytes']);
        }

        return true;
    }


}

LogProbToken.RequiredProperties = ["token", "logprob", "bytes"];

/**
 * @member {String} token
 */
LogProbToken.prototype['token'] = undefined;

/**
 * @member {Number} logprob
 */
LogProbToken.prototype['logprob'] = undefined;

/**
 * @member {Array.<Number>} bytes
 */
LogProbToken.prototype['bytes'] = undefined;






export default LogProbToken;

