/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemGPTUsageStatistics model module.
 * @module model/MemGPTUsageStatistics
 * @version 0.1.0
 */
class MemGPTUsageStatistics {
    /**
     * Constructs a new <code>MemGPTUsageStatistics</code>.
     * @alias module:model/MemGPTUsageStatistics
     */
    constructor() { 
        
        MemGPTUsageStatistics.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemGPTUsageStatistics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemGPTUsageStatistics} obj Optional instance to populate.
     * @return {module:model/MemGPTUsageStatistics} The populated <code>MemGPTUsageStatistics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemGPTUsageStatistics();

            if (data.hasOwnProperty('completion_tokens')) {
                obj['completion_tokens'] = ApiClient.convertToType(data['completion_tokens'], 'Number');
            }
            if (data.hasOwnProperty('prompt_tokens')) {
                obj['prompt_tokens'] = ApiClient.convertToType(data['prompt_tokens'], 'Number');
            }
            if (data.hasOwnProperty('total_tokens')) {
                obj['total_tokens'] = ApiClient.convertToType(data['total_tokens'], 'Number');
            }
            if (data.hasOwnProperty('step_count')) {
                obj['step_count'] = ApiClient.convertToType(data['step_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemGPTUsageStatistics</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemGPTUsageStatistics</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The number of tokens generated by the agent.
 * @member {Number} completion_tokens
 * @default 0
 */
MemGPTUsageStatistics.prototype['completion_tokens'] = 0;

/**
 * The number of tokens in the prompt.
 * @member {Number} prompt_tokens
 * @default 0
 */
MemGPTUsageStatistics.prototype['prompt_tokens'] = 0;

/**
 * The total number of tokens processed by the agent.
 * @member {Number} total_tokens
 * @default 0
 */
MemGPTUsageStatistics.prototype['total_tokens'] = 0;

/**
 * The number of steps taken by the agent.
 * @member {Number} step_count
 * @default 0
 */
MemGPTUsageStatistics.prototype['step_count'] = 0;






export default MemGPTUsageStatistics;

