/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Block from './Block';

/**
 * The Memory model module.
 * @module model/Memory
 * @version 0.1.0
 */
class Memory {
    /**
     * Constructs a new <code>Memory</code>.
     * Represents the in-context memory of the agent
     * @alias module:model/Memory
     */
    constructor() { 
        
        Memory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Memory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Memory} obj Optional instance to populate.
     * @return {module:model/Memory} The populated <code>Memory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Memory();

            if (data.hasOwnProperty('memory')) {
                obj['memory'] = ApiClient.convertToType(data['memory'], {'String': Block});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Memory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Memory</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Mapping from memory block section to memory block.
 * @member {Object.<String, module:model/Block>} memory
 */
Memory.prototype['memory'] = undefined;






export default Memory;

