/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageFile model module.
 * @module model/MessageFile
 * @version 0.1.0
 */
class MessageFile {
    /**
     * Constructs a new <code>MessageFile</code>.
     * @alias module:model/MessageFile
     * @param id {String} The unique identifier of the file.
     * @param createdAt {Number} The unix timestamp of when the file was created.
     * @param messageId {String} The unique identifier of the message.
     */
    constructor(id, createdAt, messageId) { 
        
        MessageFile.initialize(this, id, createdAt, messageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, messageId) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['message_id'] = messageId;
    }

    /**
     * Constructs a <code>MessageFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageFile} obj Optional instance to populate.
     * @return {module:model/MessageFile} The populated <code>MessageFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageFile();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('message_id')) {
                obj['message_id'] = ApiClient.convertToType(data['message_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageFile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageFile</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MessageFile.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['message_id'] && !(typeof data['message_id'] === 'string' || data['message_id'] instanceof String)) {
            throw new Error("Expected the field `message_id` to be a primitive type in the JSON string but got " + data['message_id']);
        }

        return true;
    }


}

MessageFile.RequiredProperties = ["id", "created_at", "message_id"];

/**
 * The unique identifier of the file.
 * @member {String} id
 */
MessageFile.prototype['id'] = undefined;

/**
 * @member {String} object
 * @default 'thread.message.file'
 */
MessageFile.prototype['object'] = 'thread.message.file';

/**
 * The unix timestamp of when the file was created.
 * @member {Number} created_at
 */
MessageFile.prototype['created_at'] = undefined;

/**
 * The unique identifier of the message.
 * @member {String} message_id
 */
MessageFile.prototype['message_id'] = undefined;






export default MessageFile;

