/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageRole from './MessageRole';

/**
 * The MessageCreate model module.
 * @module model/MessageCreate
 * @version 0.1.0
 */
class MessageCreate {
    /**
     * Constructs a new <code>MessageCreate</code>.
     * Request to create a message
     * @alias module:model/MessageCreate
     * @param role {module:model/MessageRole} The role of the participant.
     * @param text {String} The text of the message.
     */
    constructor(role, text) { 
        
        MessageCreate.initialize(this, role, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, role, text) { 
        obj['role'] = role;
        obj['text'] = text;
    }

    /**
     * Constructs a <code>MessageCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageCreate} obj Optional instance to populate.
     * @return {module:model/MessageCreate} The populated <code>MessageCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageCreate();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], MessageRole);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MessageCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

MessageCreate.RequiredProperties = ["role", "text"];

/**
 * The role of the participant.
 * @member {module:model/MessageRole} role
 */
MessageCreate.prototype['role'] = undefined;

/**
 * The text of the message.
 * @member {String} text
 */
MessageCreate.prototype['text'] = undefined;

/**
 * @member {String} name
 */
MessageCreate.prototype['name'] = undefined;






export default MessageCreate;

