/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MessageRole.
* @enum {}
* @readonly
*/
export default class MessageRole {
    
        /**
         * value: "assistant"
         * @const
         */
        "assistant" = "assistant";

    
        /**
         * value: "user"
         * @const
         */
        "user" = "user";

    
        /**
         * value: "tool"
         * @const
         */
        "tool" = "tool";

    
        /**
         * value: "function"
         * @const
         */
        "function" = "function";

    
        /**
         * value: "system"
         * @const
         */
        "system" = "system";

    

    /**
    * Returns a <code>MessageRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MessageRole} The enum <code>MessageRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

