/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FunctionCall1 from './FunctionCall1';
import FunctionCallMessage from './FunctionCallMessage';
import FunctionReturn from './FunctionReturn';
import InternalMonologue from './InternalMonologue';
// TODO: add anyof model support
