/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModifyMessageRequest model module.
 * @module model/ModifyMessageRequest
 * @version 0.1.0
 */
class ModifyMessageRequest {
    /**
     * Constructs a new <code>ModifyMessageRequest</code>.
     * @alias module:model/ModifyMessageRequest
     */
    constructor() { 
        
        ModifyMessageRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModifyMessageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyMessageRequest} obj Optional instance to populate.
     * @return {module:model/ModifyMessageRequest} The populated <code>ModifyMessageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyMessageRequest();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModifyMessageRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModifyMessageRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Metadata associated with the message.
 * @member {Object} metadata
 */
ModifyMessageRequest.prototype['metadata'] = undefined;






export default ModifyMessageRequest;

