/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OpenAIUsage model module.
 * @module model/OpenAIUsage
 * @version 0.1.0
 */
class OpenAIUsage {
    /**
     * Constructs a new <code>OpenAIUsage</code>.
     * @alias module:model/OpenAIUsage
     * @param completionTokens {Number} The number of tokens used for the run.
     * @param promptTokens {Number} The number of tokens used for the prompt.
     * @param totalTokens {Number} The total number of tokens used for the run.
     */
    constructor(completionTokens, promptTokens, totalTokens) { 
        
        OpenAIUsage.initialize(this, completionTokens, promptTokens, totalTokens);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, completionTokens, promptTokens, totalTokens) { 
        obj['completion_tokens'] = completionTokens;
        obj['prompt_tokens'] = promptTokens;
        obj['total_tokens'] = totalTokens;
    }

    /**
     * Constructs a <code>OpenAIUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OpenAIUsage} obj Optional instance to populate.
     * @return {module:model/OpenAIUsage} The populated <code>OpenAIUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenAIUsage();

            if (data.hasOwnProperty('completion_tokens')) {
                obj['completion_tokens'] = ApiClient.convertToType(data['completion_tokens'], 'Number');
            }
            if (data.hasOwnProperty('prompt_tokens')) {
                obj['prompt_tokens'] = ApiClient.convertToType(data['prompt_tokens'], 'Number');
            }
            if (data.hasOwnProperty('total_tokens')) {
                obj['total_tokens'] = ApiClient.convertToType(data['total_tokens'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OpenAIUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OpenAIUsage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OpenAIUsage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

OpenAIUsage.RequiredProperties = ["completion_tokens", "prompt_tokens", "total_tokens"];

/**
 * The number of tokens used for the run.
 * @member {Number} completion_tokens
 */
OpenAIUsage.prototype['completion_tokens'] = undefined;

/**
 * The number of tokens used for the prompt.
 * @member {Number} prompt_tokens
 */
OpenAIUsage.prototype['prompt_tokens'] = undefined;

/**
 * The total number of tokens used for the run.
 * @member {Number} total_tokens
 */
OpenAIUsage.prototype['total_tokens'] = undefined;






export default OpenAIUsage;

