/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MemgptSchemasOpenaiOpenaiToolCall from './MemgptSchemasOpenaiOpenaiToolCall';

/**
 * The RequiredAction model module.
 * @module model/RequiredAction
 * @version 0.1.0
 */
class RequiredAction {
    /**
     * Constructs a new <code>RequiredAction</code>.
     * @alias module:model/RequiredAction
     * @param submitToolOutputs {Array.<module:model/MemgptSchemasOpenaiOpenaiToolCall>} 
     */
    constructor(submitToolOutputs) { 
        
        RequiredAction.initialize(this, submitToolOutputs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, submitToolOutputs) { 
        obj['submit_tool_outputs'] = submitToolOutputs;
    }

    /**
     * Constructs a <code>RequiredAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequiredAction} obj Optional instance to populate.
     * @return {module:model/RequiredAction} The populated <code>RequiredAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequiredAction();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('submit_tool_outputs')) {
                obj['submit_tool_outputs'] = ApiClient.convertToType(data['submit_tool_outputs'], [MemgptSchemasOpenaiOpenaiToolCall]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequiredAction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequiredAction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RequiredAction.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        if (data['submit_tool_outputs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['submit_tool_outputs'])) {
                throw new Error("Expected the field `submit_tool_outputs` to be an array in the JSON data but got " + data['submit_tool_outputs']);
            }
            // validate the optional field `submit_tool_outputs` (array)
            for (const item of data['submit_tool_outputs']) {
                MemgptSchemasOpenaiOpenaiToolCall.validateJSON(item);
            };
        }

        return true;
    }


}

RequiredAction.RequiredProperties = ["submit_tool_outputs"];

/**
 * @member {String} type
 * @default 'submit_tool_outputs'
 */
RequiredAction.prototype['type'] = 'submit_tool_outputs';

/**
 * @member {Array.<module:model/MemgptSchemasOpenaiOpenaiToolCall>} submit_tool_outputs
 */
RequiredAction.prototype['submit_tool_outputs'] = undefined;






export default RequiredAction;

