/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmbeddingConfig from './EmbeddingConfig';

/**
 * The SourceCreate model module.
 * @module model/SourceCreate
 * @version 0.1.0
 */
class SourceCreate {
    /**
     * Constructs a new <code>SourceCreate</code>.
     * @alias module:model/SourceCreate
     * @param name {String} The name of the source.
     */
    constructor(name) { 
        
        SourceCreate.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>SourceCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceCreate} obj Optional instance to populate.
     * @return {module:model/SourceCreate} The populated <code>SourceCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceCreate();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('embedding_config')) {
                obj['embedding_config'] = EmbeddingConfig.constructFromObject(data['embedding_config']);
            }
            if (data.hasOwnProperty('metadata_')) {
                obj['metadata_'] = ApiClient.convertToType(data['metadata_'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SourceCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SourceCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SourceCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `embedding_config`
        if (data['embedding_config']) { // data not null
          EmbeddingConfig.validateJSON(data['embedding_config']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

SourceCreate.RequiredProperties = ["name"];

/**
 * @member {String} description
 */
SourceCreate.prototype['description'] = undefined;

/**
 * @member {module:model/EmbeddingConfig} embedding_config
 */
SourceCreate.prototype['embedding_config'] = undefined;

/**
 * @member {Object} metadata_
 */
SourceCreate.prototype['metadata_'] = undefined;

/**
 * The name of the source.
 * @member {String} name
 */
SourceCreate.prototype['name'] = undefined;






export default SourceCreate;

