/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmbeddingConfig from './EmbeddingConfig';

/**
 * The SourceUpdate model module.
 * @module model/SourceUpdate
 * @version 0.1.0
 */
class SourceUpdate {
    /**
     * Constructs a new <code>SourceUpdate</code>.
     * @alias module:model/SourceUpdate
     * @param id {String} The ID of the source.
     */
    constructor(id) { 
        
        SourceUpdate.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>SourceUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceUpdate} obj Optional instance to populate.
     * @return {module:model/SourceUpdate} The populated <code>SourceUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceUpdate();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('embedding_config')) {
                obj['embedding_config'] = EmbeddingConfig.constructFromObject(data['embedding_config']);
            }
            if (data.hasOwnProperty('metadata_')) {
                obj['metadata_'] = ApiClient.convertToType(data['metadata_'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SourceUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SourceUpdate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SourceUpdate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `embedding_config`
        if (data['embedding_config']) { // data not null
          EmbeddingConfig.validateJSON(data['embedding_config']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

SourceUpdate.RequiredProperties = ["id"];

/**
 * @member {String} description
 */
SourceUpdate.prototype['description'] = undefined;

/**
 * @member {module:model/EmbeddingConfig} embedding_config
 */
SourceUpdate.prototype['embedding_config'] = undefined;

/**
 * @member {Object} metadata_
 */
SourceUpdate.prototype['metadata_'] = undefined;

/**
 * The ID of the source.
 * @member {String} id
 */
SourceUpdate.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SourceUpdate.prototype['name'] = undefined;






export default SourceUpdate;

