/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EmbeddingConfig from '../model/EmbeddingConfig';
import LLMConfig from '../model/LLMConfig';

/**
* Config service.
* @module api/ConfigApi
* @version 0.1.0
*/
export default class ConfigApi {

    /**
    * Constructs a new ConfigApi. 
    * @alias module:api/ConfigApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getEmbeddingConfigsApiConfigEmbeddingGet operation.
     * @callback module:api/ConfigApi~getEmbeddingConfigsApiConfigEmbeddingGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/EmbeddingConfig>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Embedding Configs
     * Retrieve the base configuration for the server.
     * @param {module:api/ConfigApi~getEmbeddingConfigsApiConfigEmbeddingGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/EmbeddingConfig>}
     */
    getEmbeddingConfigsApiConfigEmbeddingGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [EmbeddingConfig];
      return this.apiClient.callApi(
        '/api/config/embedding', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLlmConfigsApiConfigLlmGet operation.
     * @callback module:api/ConfigApi~getLlmConfigsApiConfigLlmGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/LLMConfig>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Llm Configs
     * Retrieve the base configuration for the server.
     * @param {module:api/ConfigApi~getLlmConfigsApiConfigLlmGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/LLMConfig>}
     */
    getLlmConfigsApiConfigLlmGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['HTTPBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LLMConfig];
      return this.apiClient.callApi(
        '/api/config/llm', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
