/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiAssistantsApi);
  }
}(this, function(expect, OpenAiAssistantsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiAssistantsApi.CreateAssistantRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateAssistantRequest', function() {
    it('should create an instance of CreateAssistantRequest', function() {
      // uncomment below and update the code to test CreateAssistantRequest
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be.a(OpenAiAssistantsApi.CreateAssistantRequest);
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property instructions (base name: "instructions")', function() {
      // uncomment below and update the code to test the property instructions
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property tools (base name: "tools")', function() {
      // uncomment below and update the code to test the property tools
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property fileIds (base name: "file_ids")', function() {
      // uncomment below and update the code to test the property fileIds
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

    it('should have the property embeddingModel (base name: "embedding_model")', function() {
      // uncomment below and update the code to test the property embeddingModel
      //var instance = new OpenAiAssistantsApi.CreateAssistantRequest();
      //expect(instance).to.be();
    });

  });

}));
