/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiAssistantsApi);
  }
}(this, function(expect, OpenAiAssistantsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiAssistantsApi.EmbeddingConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmbeddingConfig', function() {
    it('should create an instance of EmbeddingConfig', function() {
      // uncomment below and update the code to test EmbeddingConfig
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be.a(OpenAiAssistantsApi.EmbeddingConfig);
    });

    it('should have the property embeddingEndpointType (base name: "embedding_endpoint_type")', function() {
      // uncomment below and update the code to test the property embeddingEndpointType
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property embeddingEndpoint (base name: "embedding_endpoint")', function() {
      // uncomment below and update the code to test the property embeddingEndpoint
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property embeddingModel (base name: "embedding_model")', function() {
      // uncomment below and update the code to test the property embeddingModel
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property embeddingDim (base name: "embedding_dim")', function() {
      // uncomment below and update the code to test the property embeddingDim
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property embeddingChunkSize (base name: "embedding_chunk_size")', function() {
      // uncomment below and update the code to test the property embeddingChunkSize
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property azureEndpoint (base name: "azure_endpoint")', function() {
      // uncomment below and update the code to test the property azureEndpoint
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property azureVersion (base name: "azure_version")', function() {
      // uncomment below and update the code to test the property azureVersion
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

    it('should have the property azureDeployment (base name: "azure_deployment")', function() {
      // uncomment below and update the code to test the property azureDeployment
      //var instance = new OpenAiAssistantsApi.EmbeddingConfig();
      //expect(instance).to.be();
    });

  });

}));
