/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiAssistantsApi);
  }
}(this, function(expect, OpenAiAssistantsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiAssistantsApi.AdminApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminApi', function() {
    describe('createNewApiKeyAdminUsersKeysPost', function() {
      it('should call createNewApiKeyAdminUsersKeysPost successfully', function(done) {
        //uncomment below and update the code to test createNewApiKeyAdminUsersKeysPost
        //instance.createNewApiKeyAdminUsersKeysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUserAdminUsersPost', function() {
      it('should call createUserAdminUsersPost successfully', function(done) {
        //uncomment below and update the code to test createUserAdminUsersPost
        //instance.createUserAdminUsersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteApiKeyAdminUsersKeysDelete', function() {
      it('should call deleteApiKeyAdminUsersKeysDelete successfully', function(done) {
        //uncomment below and update the code to test deleteApiKeyAdminUsersKeysDelete
        //instance.deleteApiKeyAdminUsersKeysDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserAdminUsersDelete', function() {
      it('should call deleteUserAdminUsersDelete successfully', function(done) {
        //uncomment below and update the code to test deleteUserAdminUsersDelete
        //instance.deleteUserAdminUsersDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsersAdminUsersGet', function() {
      it('should call getAllUsersAdminUsersGet successfully', function(done) {
        //uncomment below and update the code to test getAllUsersAdminUsersGet
        //instance.getAllUsersAdminUsersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiKeysAdminUsersKeysGet', function() {
      it('should call getApiKeysAdminUsersKeysGet successfully', function(done) {
        //uncomment below and update the code to test getApiKeysAdminUsersKeysGet
        //instance.getApiKeysAdminUsersKeysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
