/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiAssistantsApi);
  }
}(this, function(expect, OpenAiAssistantsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiAssistantsApi.AgentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AgentsApi', function() {
    describe('createAgentApiAgentsPost', function() {
      it('should call createAgentApiAgentsPost successfully', function(done) {
        //uncomment below and update the code to test createAgentApiAgentsPost
        //instance.createAgentApiAgentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAgentApiAgentsAgentIdDelete', function() {
      it('should call deleteAgentApiAgentsAgentIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteAgentApiAgentsAgentIdDelete
        //instance.deleteAgentApiAgentsAgentIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAgentArchivalMemoryApiAgentsAgentIdArchivalMemoryIdDelete', function() {
      it('should call deleteAgentArchivalMemoryApiAgentsAgentIdArchivalMemoryIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteAgentArchivalMemoryApiAgentsAgentIdArchivalMemoryIdDelete
        //instance.deleteAgentArchivalMemoryApiAgentsAgentIdArchivalMemoryIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentArchivalMemoryApiAgentsAgentIdArchivalGet', function() {
      it('should call getAgentArchivalMemoryApiAgentsAgentIdArchivalGet successfully', function(done) {
        //uncomment below and update the code to test getAgentArchivalMemoryApiAgentsAgentIdArchivalGet
        //instance.getAgentArchivalMemoryApiAgentsAgentIdArchivalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentArchivalMemorySummaryApiAgentsAgentIdMemoryArchivalGet', function() {
      it('should call getAgentArchivalMemorySummaryApiAgentsAgentIdMemoryArchivalGet successfully', function(done) {
        //uncomment below and update the code to test getAgentArchivalMemorySummaryApiAgentsAgentIdMemoryArchivalGet
        //instance.getAgentArchivalMemorySummaryApiAgentsAgentIdMemoryArchivalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentInContextMessagesApiAgentsAgentIdMemoryMessagesGet', function() {
      it('should call getAgentInContextMessagesApiAgentsAgentIdMemoryMessagesGet successfully', function(done) {
        //uncomment below and update the code to test getAgentInContextMessagesApiAgentsAgentIdMemoryMessagesGet
        //instance.getAgentInContextMessagesApiAgentsAgentIdMemoryMessagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentMemoryApiAgentsAgentIdMemoryGet', function() {
      it('should call getAgentMemoryApiAgentsAgentIdMemoryGet successfully', function(done) {
        //uncomment below and update the code to test getAgentMemoryApiAgentsAgentIdMemoryGet
        //instance.getAgentMemoryApiAgentsAgentIdMemoryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentMessagesApiAgentsAgentIdMessagesGet', function() {
      it('should call getAgentMessagesApiAgentsAgentIdMessagesGet successfully', function(done) {
        //uncomment below and update the code to test getAgentMessagesApiAgentsAgentIdMessagesGet
        //instance.getAgentMessagesApiAgentsAgentIdMessagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentMessagesInContextApiAgentsAgentIdMessagesContextGet', function() {
      it('should call getAgentMessagesInContextApiAgentsAgentIdMessagesContextGet successfully', function(done) {
        //uncomment below and update the code to test getAgentMessagesInContextApiAgentsAgentIdMessagesContextGet
        //instance.getAgentMessagesInContextApiAgentsAgentIdMessagesContextGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentRecallMemorySummaryApiAgentsAgentIdMemoryRecallGet', function() {
      it('should call getAgentRecallMemorySummaryApiAgentsAgentIdMemoryRecallGet successfully', function(done) {
        //uncomment below and update the code to test getAgentRecallMemorySummaryApiAgentsAgentIdMemoryRecallGet
        //instance.getAgentRecallMemorySummaryApiAgentsAgentIdMemoryRecallGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentSourcesApiAgentsAgentIdSourcesGet', function() {
      it('should call getAgentSourcesApiAgentsAgentIdSourcesGet successfully', function(done) {
        //uncomment below and update the code to test getAgentSourcesApiAgentsAgentIdSourcesGet
        //instance.getAgentSourcesApiAgentsAgentIdSourcesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAgentStateApiAgentsAgentIdGet', function() {
      it('should call getAgentStateApiAgentsAgentIdGet successfully', function(done) {
        //uncomment below and update the code to test getAgentStateApiAgentsAgentIdGet
        //instance.getAgentStateApiAgentsAgentIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllAgentsApiAdminAgentsGet', function() {
      it('should call getAllAgentsApiAdminAgentsGet successfully', function(done) {
        //uncomment below and update the code to test getAllAgentsApiAdminAgentsGet
        //instance.getAllAgentsApiAdminAgentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertAgentArchivalMemoryApiAgentsAgentIdArchivalPost', function() {
      it('should call insertAgentArchivalMemoryApiAgentsAgentIdArchivalPost successfully', function(done) {
        //uncomment below and update the code to test insertAgentArchivalMemoryApiAgentsAgentIdArchivalPost
        //instance.insertAgentArchivalMemoryApiAgentsAgentIdArchivalPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAgentsApiAgentsGet', function() {
      it('should call listAgentsApiAgentsGet successfully', function(done) {
        //uncomment below and update the code to test listAgentsApiAgentsGet
        //instance.listAgentsApiAgentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendMessageApiAgentsAgentIdMessagesPost', function() {
      it('should call sendMessageApiAgentsAgentIdMessagesPost successfully', function(done) {
        //uncomment below and update the code to test sendMessageApiAgentsAgentIdMessagesPost
        //instance.sendMessageApiAgentsAgentIdMessagesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAgentApiAgentsAgentIdPost', function() {
      it('should call updateAgentApiAgentsAgentIdPost successfully', function(done) {
        //uncomment below and update the code to test updateAgentApiAgentsAgentIdPost
        //instance.updateAgentApiAgentsAgentIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAgentMemoryApiAgentsAgentIdMemoryPost', function() {
      it('should call updateAgentMemoryApiAgentsAgentIdMemoryPost successfully', function(done) {
        //uncomment below and update the code to test updateAgentMemoryApiAgentsAgentIdMemoryPost
        //instance.updateAgentMemoryApiAgentsAgentIdMemoryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
