/**
 * OpenAI Assistants API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiAssistantsApi);
  }
}(this, function(expect, OpenAiAssistantsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiAssistantsApi.ToolsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ToolsApi', function() {
    describe('createToolAdminToolsPost', function() {
      it('should call createToolAdminToolsPost successfully', function(done) {
        //uncomment below and update the code to test createToolAdminToolsPost
        //instance.createToolAdminToolsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createToolApiToolsPost', function() {
      it('should call createToolApiToolsPost successfully', function(done) {
        //uncomment below and update the code to test createToolApiToolsPost
        //instance.createToolApiToolsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteToolAdminToolsToolNameDelete', function() {
      it('should call deleteToolAdminToolsToolNameDelete successfully', function(done) {
        //uncomment below and update the code to test deleteToolAdminToolsToolNameDelete
        //instance.deleteToolAdminToolsToolNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteToolApiToolsToolIdDelete', function() {
      it('should call deleteToolApiToolsToolIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteToolApiToolsToolIdDelete
        //instance.deleteToolApiToolsToolIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getToolAdminToolsToolNameGet', function() {
      it('should call getToolAdminToolsToolNameGet successfully', function(done) {
        //uncomment below and update the code to test getToolAdminToolsToolNameGet
        //instance.getToolAdminToolsToolNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getToolApiToolsToolIdGet', function() {
      it('should call getToolApiToolsToolIdGet successfully', function(done) {
        //uncomment below and update the code to test getToolApiToolsToolIdGet
        //instance.getToolApiToolsToolIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getToolIdApiToolsNameToolNameGet', function() {
      it('should call getToolIdApiToolsNameToolNameGet successfully', function(done) {
        //uncomment below and update the code to test getToolIdApiToolsNameToolNameGet
        //instance.getToolIdApiToolsNameToolNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllToolsAdminToolsGet', function() {
      it('should call listAllToolsAdminToolsGet successfully', function(done) {
        //uncomment below and update the code to test listAllToolsAdminToolsGet
        //instance.listAllToolsAdminToolsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllToolsApiToolsGet', function() {
      it('should call listAllToolsApiToolsGet successfully', function(done) {
        //uncomment below and update the code to test listAllToolsApiToolsGet
        //instance.listAllToolsApiToolsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateToolApiToolsToolIdPost', function() {
      it('should call updateToolApiToolsToolIdPost successfully', function(done) {
        //uncomment below and update the code to test updateToolApiToolsToolIdPost
        //instance.updateToolApiToolsToolIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
